Repository Rjndrkha/Data-Structure_Code-Programm, pull requests merged in 2021-10, with the labels that each got.

#1 Create TempheraturCalculator.java
  TempheraturCalculator.java
Labels: hacktoberfest-accepted

#3 Create TubeCalculator.java
  TubeCalculator.java
Labels: hacktoberfest-accepted

#5 Add program to check Prime Number and print Fibonacci Series
  .gitignore
  Fibonacci.java
  Prime.java
Labels: hacktoberfest-accepted

#4 Create ArrayInputLoop.java
  ArrayInputLoop.java
  AverageCalculator.java
Labels: hacktoberfest-accepted

#6 add StarNestedFor.java
  DoWhile.java
  StarNestedFor.java
Labels: hacktoberfest-accepted

#9 Create generateToken.js
  generateToken.js
Labels: hacktoberfest-accepted

#8 Create sorting.java
  sorting.java
Labels: hacktoberfest-accepted

#7 Create DeleteElement.java
  DeleteElement.java
Labels: hacktoberfest-accepted

#12 Artificial Assistant in Python
  Friday.py
Labels: hacktoberfest-accepted

#11 Added Sorting Algo
  bubbleSort.java
Labels: hacktoberfest-accepted

#13 Added java Program to implement linear search
  LinearSearchExample.java
Labels: hacktoberfest-accepted

#10 Create LICENSE.md
  LICENSE.md
Labels: hacktoberfest-accepted

#14 Add files via upload
  armstrong.java
Labels: hacktoberfest-accepted

#15 Recursive_Bubble_Sort
  JAVA/Recursive_Bubble_Sort.java
Labels: hacktoberfest-accepted

#19 Bitonic Sort.java
  JAVA/Bitonic Sort.java
Labels: hacktoberfest-accepted

#18 Create maxprofit.py
  PYTHON/maxprofit.py
Labels: hacktoberfest-accepted

#17 added some files
  C/Queus.c
  C/Stacks.c
  PYTHON/Fetch HTTP status code.py
  PYTHON/generate_barcode.py
  PYTHON/generatepassword.py
  PYTHON/texttohandwritten.py
  PYTHON/typingspeed.py
Labels: hacktoberfest-accepted

#16 Recursive_Insertion_Sort
  JAVA/Recursive_Insertion_Sort.java
Labels: hacktoberfest-accepted

#20 Counting Sort.java
  JAVA/Counting Sort.java
Labels: hacktoberfest-accepted

#28 Add files via upload
  Array_subset_of_another_array.py
Labels: hacktoberfest-accepted

#27 TreeSort.java
  JAVA/Tree Sort.java
Labels: hacktoberfest-accepted

#26 reverseofarray
  JAVA/Reversearray.java
Labels: hacktoberfest-accepted

#21 ShellSort.java
  JAVA/ShellSort.java
Labels: hacktoberfest-accepted

#25 TimSort.java
  JAVA/TimSort.java
Labels: hacktoberfest-accepted

#24 Gnome Sort.java
  JAVA/Gnome Sort.java
Labels: hacktoberfest-accepted

#23 Created Searching for specific number in 1D array
  C/Searching for specific number in 1D array.c
Labels: hacktoberfest-accepted

#22 Check Palindrome Recursive.py
  PYTHON/Check Palindrome Recursive.py
Labels: hacktoberfest-accepted

#31 Create BinarySearch.java
  JAVA/BinarySearch.java
Labels: hacktoberfest-accepted

#30 SumOfDigits.py
  PYTHON/SumOfDigits.py
Labels: hacktoberfest-accepted

#29 py script to grab your *current ip
  PYTHON/my_ip.py
  PYTHON/qr_code_gen.py
Labels: hacktoberfest-accepted

#32 Insertion_sort.py
  Insertion sort
Labels: hacktoberfest-accepted

#33 email sender
  PYTHON/email.py
Labels: hacktoberfest-accepted

#35 [Java] Guest Number App
  JAVA/GuessNumberApp.java
Labels: hacktoberfest-accepted

#34 Add files via upload
  PYTHON/search.py
Labels: hacktoberfest-accepted

#36 Create ShuffleAndDrawCards.py
  PYTHON/ShuffleAndDrawCards.py
Labels: hacktoberfest-accepted

#37 Chrome Extension that shows Jokes
  JS/chrome-extension/css/style.css
  JS/chrome-extension/icon.png
  JS/chrome-extension/js/joke.js
  JS/chrome-extension/manifest.json
  JS/chrome-extension/popup.html
Labels: hacktoberfest-accepted

#38 MultiplicationRecursive.py
  PYTHON/MultiplicationRecursive.py
Labels: hacktoberfest-accepted

#41 Create Zig-Zag.py
  PYTHON/Zig-Zag.py
Labels: hacktoberfest-accepted

#45 Added 1 html & 1 java file
  HTML/registration-form.html
  JAVA/kadane's_Algorithm.java
Labels: hacktoberfest-accepted

#39 Create Reflection.c
  C/Reflection.c
Labels: hacktoberfest-accepted

#40 created number series even odd calculator
  C/SimpleCalculator.c
  HTML/Mycalculator/index.html
  HTML/Mycalculator/script.js
  HTML/Mycalculator/style.css
Labels: hacktoberfest-accepted

#44 StringToInteger.py
  PYTHON/StringToInteger.py
Labels: hacktoberfest-accepted

#43 Create Binary Tree Maximum Path Sum
  JAVA/Binary Tree Maximum Path Sum
Labels: hacktoberfest-accepted

#42 updated DoWhile.java
  JAVA/DoWhile.java
Labels: hacktoberfest-accepted

#52 Weather updates python script
  PYTHON/WeatherUpdates.py
Labels: hacktoberfest-accepted

#51 Added egg dropping problem in java folder
  JAVA/egg-dropping-puzzle.java
Labels: hacktoberfest-accepted

#49 Create TowerOfHanoi.java
  JAVA/TowerOfHanoi.java
Labels: hacktoberfest-accepted

#48 Create ArmstrongNumber.c
  C/ArmstrongNumber.c
Labels: hacktoberfest-accepted

#47 Create MergeSort.java
  JAVA/MergeSort.java
Labels: hacktoberfest-accepted

#46 1-liner for Leetcode#2011
  JAVA/FinalValueofVariableAfterPerformingOperations.java
Labels: hacktoberfest-accepted

#56 Digital Clock Ready to Run
  Digital  Clock/Digital Clock.html
  Digital  Clock/Logic.js
  Digital  Clock/style.css
Labels: hacktoberfest-accepted

#55 Created C++ code to find factorial
  cpp/factorial.cpp
Labels: hacktoberfest-accepted

#54 Create advanced_password_generator.py
  PYTHON/advanced_password_generator.py
Labels: hacktoberfest-accepted

#57 Java Program To Check whether No is Palindrome or not
  JAVA/Palindrome.java
Labels: hacktoberfest-accepted

#58 Added Two Sum problem - Java
  JAVA/TwoSum.java
Labels: hacktoberfest-accepted

#59 Create Palindrome.java
  JAVA/Numberpattern.java
  JAVA/Palindrome.java
  PYTHON/Calculator.py
Labels: hacktoberfest-accepted

#62 Create LargestofThreeNumbers.cpp
  cpp/LargestofThreeNumbers.cpp
Labels: hacktoberfest-accepted

#61 Create Basic string .c
  C/printstringusingarray.c
Labels: hacktoberfest-accepted

#60 Java Program to ADD two Matrices
  JAVA/AddMatrices.java
Labels: hacktoberfest-accepted

#64 Reversing an Arrays
  JAVA/Reversing_Arrays.java
Labels: hacktoberfest-accepted

#63 Triplet Sum.java
  JAVA/Triplet Sum.java
Labels: hacktoberfest-accepted

#65 Create Fascinating.java
  JAVA/Fascinating.java
Labels: hacktoberfest-accepted

#67 Add files via upload
  C/InsertionSort.c
  JAVA/MinMaxIn2D.java
Labels: hacktoberfest-accepted

#66 Doubly Linked List in C++
  cpp/DoublyLinkedList.cpp
Labels: hacktoberfest-accepted

#68 ARRAYlar.java
  ARRAYlar.java
Labels: hacktoberfest-accepted

#78 Added python program
  .DS_Store
  PYTHON/BT - 1.ipynb
  PYTHON/BT-2.ipynb
  PYTHON/Complete OOPS.ipynb
  PYTHON/Linked List.ipynb
  PYTHON/Queue - all algo.ipynb
  PYTHON/Search Sort Recurision.ipynb
  PYTHON/Stack.ipynb
Labels: hacktoberfest-accepted

#77 bubblesort
  bubble11sort.c
Labels: hacktoberfest-accepted

#76 Added Breadth First Search or BFS for a Graph
  cpp/BFS
Labels: hacktoberfest-accepted

#75 Learn computer graphics
  cpp/Computer Graphics - Day 2.cpp
  cpp/Computer Graphics - Day 3.cpp
  cpp/Computer Graphics - Day 4.cpp
  cpp/Computer Graphics - TRIANGLE.cpp
Labels: hacktoberfest-accepted

#74 First and Last Position of Element in Sorted Array Sol
  JAVA/Find First and Last Position of Element in Sorted Array.java
Labels: hacktoberfest-accepted

#73 Responsive footer.html
  HTML/Responsive footer.html
Labels: hacktoberfest-accepted

#72 Find Minimum in Rotated Sorted Array II(leetcode hard) solution.java
  JAVA/Find Minimum in Rotated Sorted Array II(leetcode hard) solution.java
Labels: hacktoberfest-accepted

#71 C++ Program to perform Deletion in Array
  cpp/Deletion_In_Array.cpp
Labels: hacktoberfest-accepted

#70 Add files via upload
  cpp/tsort.cpp
Labels: hacktoberfest-accepted

#69 Created Linked List Data Structure
  JAVA/Linked_List_Build.java
Labels: hacktoberfest-accepted

#79 Tic_Tac_Toe_game.py
  PYTHON/Tic_Tac_Toe_game.py
Labels: hacktoberfest-accepted

#83 Diamond star pattern
  PYTHON/star.py
Labels: hacktoberfest-accepted, automerge

#80 Create Swap 2 Numbers without using temporary variable
  JAVA/Swap 2 Numbers without using temporary variable
Labels: hacktoberfest-accepted, automerge

#82 Merge_2_dictionary
  Merge_2_dictionary.py
Labels: hacktoberfest-accepted, automerge

#81 Added Simple React Project
  React-Quiz-App/.gitignore
  React-Quiz-App/README.md
  React-Quiz-App/package-lock.json
  React-Quiz-App/package.json
  React-Quiz-App/public/favicon.ico
  React-Quiz-App/public/index.html
  React-Quiz-App/public/logo192.png
  React-Quiz-App/public/logo512.png
  React-Quiz-App/public/manifest.json
  React-Quiz-App/public/robots.txt
  React-Quiz-App/src/App.js
  React-Quiz-App/src/index.css
  React-Quiz-App/src/index.js
Labels: hacktoberfest-accepted, automerge

#84 Create ExampleVariable.java
  JAVA/ExampleVariable.java
Labels: hacktoberfest-accepted, automerge

#85 Added python program to convert text to speech
  PYTHON/text_to_speech.py
Labels: hacktoberfest-accepted, automerge

#86 Create Selection Sort
  JAVA/Selection Sort
Labels: hacktoberfest-accepted, automerge

#87 Create Magic Number
  JAVA/Magic Number
Labels: bug, hacktoberfest-accepted, automerge

#88 Created nthfibonacci
  cpp/nthfibonacci.cpp
Labels: hacktoberfest-accepted, automerge

#89 Create Special Number
  JAVA/Special Number
Labels: hacktoberfest-accepted, automerge

#90 Create CyclicSort.java
  JAVA/CyclicSort.java
Labels: hacktoberfest-accepted, automerge

#92 spiralpattern of 2d matrix
  C/Mergesort.c
  cpp/spiralprint.cpp
Labels: hacktoberfest-accepted, automerge

#91 topic modelling
  PYTHON/new topic modelling.ipynb
Labels: hacktoberfest-accepted, automerge

#93 Java Program to print Transpose of a matrix
  JAVA/Transpose.java
Labels: hacktoberfest-accepted, automerge

#95 implemented bfs in java
  JAVA/bfs.java
Labels: hacktoberfest-accepted, automerge

#96 Create Recursive linear search
  JAVA/Recursive linear search
Labels: hacktoberfest-accepted, automerge

#97 Create Reverse linked list
  JAVA/Reverse linked list
Labels: hacktoberfest-accepted, automerge

#99 Swap numbers in one line
  JAVA/swapNumbers.java
Labels: hacktoberfest-accepted, automerge

#276 Add BottomView.java
  JAVA/BottomView.java
Labels: hacktoberfest-accepted, automerge

#277 Password Generator
  PYTHON/PasswordGenerator_pawarspeaks.py
Labels: hacktoberfest-accepted, automerge

#278 added converter project
  JS/Converter/css/img/img.jpg
  JS/Converter/css/style.css
  JS/Converter/index.html
  JS/Converter/js/script.js
Labels: hacktoberfest-accepted, automerge

#279 Create text_to_speech and save in mp3 format.py
  PYTHON/text_to_speech and save in mp3 format.py
Labels: hacktoberfest-accepted, automerge

#280 Rock paper scissor_
  PYTHON/Rock paper scissor_
Labels: hacktoberfest-accepted, automerge

#281 Create Hill_climb_algo.py
  PYTHON/Hill_climb_algo.py
Labels: hacktoberfest-accepted, automerge

#282 added
  calculator.py
Labels: hacktoberfest-accepted, automerge
